services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: support_backend:latest
    container_name: support_fastapi_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: support_frontend:latest
    container_name: support_streamlit_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict
    depends_on:
      - backend
    restart: always